services:
  aerekos-redis-cache:
    image: redis:7.0.15
    container_name: aerekos-redis-cache
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data
    # networks:
    #   - aerekos-net
    restart: unless-stopped

  aerekos-redis-queue:
    image: redis:7.0.15
    container_name: aerekos-redis-queue
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6380:6379"
    volumes:
      - redis-queue-data:/data
    # networks:
    #   - aerekos-net
    restart: unless-stopped
  aerekos-neo4j:
    image: neo4j:2025.04.0
    container_name: aerekos-neo4j
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    # networks:
    #   - aerekos-net
    restart: unless-stopped

volumes:
  neo4jdata:
  neo4jlogs:
  redis-cache-data:
  redis-queue-data:

# networks:
#   aerekos-net:
#     external: true
