services:
  aerekos_redis:
    image: redis:7.4.1-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis_data:/data
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always

  aerekos_postgres:
    image: postgres:16.2-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always